databases:
  - name: ojoniter-db
    plan: free
    databaseName: ojoniter
    user: ojoniter

services:
  - type: web
    name: ojoniter
    plan: free
    runtime: docker
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ojoniter-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://ojoniter.onrender.com"
